# Generated by Django 3.2.16 on 2022-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hng', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(null=True)),
                ('num2', models.IntegerField(null=True)),
                ('operation_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='HngUserModel',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
